de.codesmile.editor.assetdatabase: CodeSmile.Editor.Asset.VersionControl Class Reference
CodeSmile.Editor.Asset.VersionControl Class Reference
Groups version control related functionality.
Static Public Member Functions
static Boolean CanMakeEditable (Object obj, StatusQueryOptions options=DefaultStatusQueryOption)
Returns true if the asset can be opened for editing in the version control system. If false, GetLastErrorMessage() returns the reason.
static void CanMakeEditable (Object[] objects, out List< String > notEditablePaths, StatusQueryOptions options=DefaultStatusQueryOption)
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
static Boolean CanMakeEditable (Path path, StatusQueryOptions options=DefaultStatusQueryOption)
Returns true if the asset can be opened for editing in the version control system. If false, GetLastErrorMessage() returns the reason.
static void CanMakeEditable (Path[] paths, out List< String > notEditablePaths, StatusQueryOptions options=DefaultStatusQueryOption)
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
static void CanMakeEditable (String[] paths, out List< String > notEditablePaths, StatusQueryOptions options=DefaultStatusQueryOption)
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
static Boolean IsEditable (Object obj, StatusQueryOptions options=DefaultStatusQueryOption)
Returns true if the asset file is open for editing in the version control system. If false, GetLastErrorMessage() contains the failure reason.
static void IsEditable (Object[] objects, out List< String > notEditablePaths, StatusQueryOptions options=DefaultStatusQueryOption)
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual objects again.
static void IsEditable (Path[] paths, out List< String > notEditablePaths, StatusQueryOptions options=DefaultStatusQueryOption)
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
static void IsEditable (String[] paths, out List< String > notEditablePaths, StatusQueryOptions options=DefaultStatusQueryOption)
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
static Boolean IsMetaEditable (Object obj, StatusQueryOptions options=DefaultStatusQueryOption)
Returns true if the meta file is open for editing in the version control system. If false, GetLastErrorMessage() contains the failure reason.
static Boolean MakeEditable (Path path)
Opens the file at path for editing in the version control system. Unity Manual
static Boolean MakeEditable (Path[] paths, out List< String > notEditablePaths)
Opens the file paths for editing in the version control system. Returns true if all could be opened. Returns false if one or more failed to open and the list of notEditablePaths. Unity Manual
static Boolean MakeEditable (String[] paths, out List< String > notEditablePaths)
Opens the file paths for editing in the version control system. Returns true if all could be opened. Returns false if one or more failed to open and the list of notEditablePaths. Unity Manual
static Boolean MakeEditableInteractive (String[] paths, out List< String > notEditablePaths, String prompt=null)
Opens the file paths for editing in the version control system. Shows a prompt to the user. Returns true if all could be opened. Returns false if one or more failed to open and the list of notEditablePaths. Unity Manual
Detailed Description
Groups version control related functionality.
Member Function Documentation
CanMakeEditable() [1/5]
static Boolean CodeSmile.Editor.Asset.VersionControl.CanMakeEditable (Object obj, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns true if the asset can be opened for editing in the version control system. If false, GetLastErrorMessage() returns the reason.
Parameters
obj
options
Returns
Asset.GetLastErrorMessage
            {
                ThrowIf.ArgumentIsNull(obj, nameof(obj));
                return CanMakeEditable(Path.Get(obj), options);
            }
References CodeSmile.Editor.Asset.VersionControl.CanMakeEditable(), and CodeSmile.Editor.Asset.Path.Get().
CanMakeEditable() [2/5]
static void CodeSmile.Editor.Asset.VersionControl.CanMakeEditable (Object[] objects, out List< String > notEditablePaths, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
Parameters
objects
notEditablePaths
options
CanMakeEditable(CodeSmile.Editor.Asset.Path,UnityEditor.StatusQueryOptions)
CanMakeEditable() [3/5]
static Boolean CodeSmile.Editor.Asset.VersionControl.CanMakeEditable (Path path, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns true if the asset can be opened for editing in the version control system. If false, GetLastErrorMessage() returns the reason.
Parameters
path
options
Returns
Asset.GetLastErrorMessage
            {
                var canOpen = AssetDatabase.CanOpenForEdit(path, out var message, options);
                if (canOpen == false)
                    SetLastErrorMessage(message);
                return canOpen;
            }
Referenced by CodeSmile.Editor.Asset.VersionControl.CanMakeEditable().
CanMakeEditable() [4/5]
static void CodeSmile.Editor.Asset.VersionControl.CanMakeEditable (Path[] paths, out List< String > notEditablePaths, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
Parameters
paths
notEditablePaths
options
CanMakeEditable(CodeSmile.Editor.Asset.Path,UnityEditor.StatusQueryOptions)
CanMakeEditable() [5/5]
static void CodeSmile.Editor.Asset.VersionControl.CanMakeEditable (String[] paths, out List< String > notEditablePaths, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
Parameters
paths
notEditablePaths
options
CanMakeEditable(CodeSmile.Editor.Asset.Path,UnityEditor.StatusQueryOptions)
            {
                notEditablePaths = new List<String>();
                AssetDatabase.CanOpenForEdit(paths, notEditablePaths, options);
            }
IsEditable() [1/4]
static Boolean CodeSmile.Editor.Asset.VersionControl.IsEditable (Object obj, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns true if the asset file is open for editing in the version control system. If false, GetLastErrorMessage() contains the failure reason.
Parameters
obj
options
Returns
            {
                var isOpen = AssetDatabase.IsOpenForEdit(obj, out var message, options);
                if (isOpen == false)
                    SetLastErrorMessage(message);
                return isOpen;
            }
IsEditable() [2/4]
static void CodeSmile.Editor.Asset.VersionControl.IsEditable (Object[] objects, out List< String > notEditablePaths, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual objects again.
Parameters
objects
notEditablePaths
options
CanMakeEditable(CodeSmile.Editor.Asset.Path,UnityEditor.StatusQueryOptions)
IsEditable() [3/4]
static void CodeSmile.Editor.Asset.VersionControl.IsEditable (Path[] paths, out List< String > notEditablePaths, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
Parameters
paths
notEditablePaths
options
CanMakeEditable(CodeSmile.Editor.Asset.Path,UnityEditor.StatusQueryOptions)
IsEditable() [4/4]
static void CodeSmile.Editor.Asset.VersionControl.IsEditable (String[] paths, out List< String > notEditablePaths, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns a list of notEditablePaths that cannot be opened for editing in the version control system. To get a reason, query the individual paths again.
Parameters
paths
notEditablePaths
options
CanMakeEditable(CodeSmile.Editor.Asset.Path,UnityEditor.StatusQueryOptions)
            {
                notEditablePaths = new List<String>();
                AssetDatabase.IsOpenForEdit(paths, notEditablePaths, options);
            }
IsMetaEditable()
static Boolean CodeSmile.Editor.Asset.VersionControl.IsMetaEditable (Object obj, StatusQueryOptions options = DefaultStatusQueryOption) static
Returns true if the meta file is open for editing in the version control system. If false, GetLastErrorMessage() contains the failure reason.
Parameters
obj
options
Returns
            {
                var isOpen = AssetDatabase.IsMetaFileOpenForEdit(obj, out var message, options);
                if (isOpen == false)
                    SetLastErrorMessage(message);
                return isOpen;
            }
MakeEditable() [1/3]
static Boolean CodeSmile.Editor.Asset.VersionControl.MakeEditable (Path path) static
Opens the file at path for editing in the version control system. Unity Manual
Parameters
path
Returns
MakeEditable() [2/3]
static Boolean CodeSmile.Editor.Asset.VersionControl.MakeEditable (Path[] paths, out List< String > notEditablePaths) static
Opens the file paths for editing in the version control system. Returns true if all could be opened. Returns false if one or more failed to open and the list of notEditablePaths. Unity Manual
Parameters
paths
notEditablePaths
Returns
MakeEditable() [3/3]
static Boolean CodeSmile.Editor.Asset.VersionControl.MakeEditable (String[] paths, out List< String > notEditablePaths) static
Opens the file paths for editing in the version control system. Returns true if all could be opened. Returns false if one or more failed to open and the list of notEditablePaths. Unity Manual
Parameters
paths
notEditablePaths
Returns
MakeEditableInteractive()
static Boolean CodeSmile.Editor.Asset.VersionControl.MakeEditableInteractive (String[] paths, out List< String > notEditablePaths, String prompt = null) static
Opens the file paths for editing in the version control system. Shows a prompt to the user. Returns true if all could be opened. Returns false if one or more failed to open and the list of notEditablePaths. Unity Manual
Parameters
paths
notEditablePaths
prompt a custom prompt or null to use default prompt
Returns
The documentation for this class was generated from the following file:
Editor/Asset.VersionControl.cs