de.codesmile.editor.assetdatabase: CodeSmile.Editor.Asset Class Reference
CodeSmile.Editor.Asset Class Reference
Classes
class Database
class Path
class SubAsset
class ThrowIf
Public Member Functions
Asset (GUID assetGuid)
Returns an instance from an existing asset's GUID.
Asset (Object obj)
Returns an instance from an existing asset reference.
Asset (Object obj, Path path, Boolean overwriteExisting=false)
Returns an instance by creating (saving) the object as an asset file at the given path. The object must not already be an asset. If it is an asset you must use the ctor without a path.
Asset (Path path)
Returns an instance from a path to an existing asset.
void AddLabel (String label)
Adds a label to the asset.
void AddLabels (String[] labels)
Adds several labels to the asset.
Boolean CanMove (Path destinationPath)
Tests if a Move operation will be successful without actually moving the asset. Note: Returns false if any of the folders to destinationPath do not exist.
void ClearLabels ()
Clears the asset's labels.
Asset Copy (Path destinationPath, Boolean overwriteExisting=false)
Makes a copy of the asset. Will create destination path folders if necessary.
Object Delete (Boolean moveToTrash=false)
Deletes the asset. Does not Destroy the object. CAUTION: The asset instance should be discarded afterwards.
Asset Duplicate ()
Creates a duplicate of the asset with a new, unique file name.
void ForceSave ()
Forces the object to be written to disk, whether it is dirty or not. Save()
T Get< T > ()
Returns MainObject cast to T, or null. But recommended usage is:
Boolean Move (Path destinationPath)
Moves asset to destination path. Any non-existing folders in destination path will be created. AssetPath property is updated accordingly.
void OpenInDefaultApplication (Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Boolean Rename (String newFileName)
Renames an asset's file or folder name. NOTE: Cannot be used to change a file's extension. Use Move instead. Move
void Save ()
Saves any changes to the object to disk if it is marked as dirty. ForceSave()
void SetMainObjectDirty ()
Marks the main object as dirty.
Object Trash ()
Moves the asset to the OS trash (same as Delete, but recoverable). Does not Destroy the object. CAUTION: The asset instance should be discarded afterwards.
Static Public Member Functions
static void AddLabel (Object obj, String label)
Adds a label to an asset's list of labels. Note: this is less efficient than SetLabels. It is provided as a convenience to add a few labels without having to do the conversion to List, then add a label, then ToArray() the list. This is what is done internally.
static void AddLabels (Object obj, String[] labels)
Adds several labels to an asset's list of labels.
static void BatchEditing (Action assetEditingAction, Boolean rethrowExceptions=false)
Speed up mass asset editing (create, modify, delete, import, etc). Within the callback action, the AssetDatabase does neither import nor auto-refresh assets. This can significantly speed up mass asset editing tasks where you work with individual assets in a loop. Internally calls Start/StopAssetEditing in a try/finally block so that exceptions will not cause the AssetDatabase to remain stopped indefinitely.
See also
https://docs.unity3d.com/Manual/AssetDatabaseBatching.html
static Boolean CanMove (Path sourcePath, Path destinationPath)
Tests if a Move operation will be successful without actually moving the asset. Note: Returns false if any of the folders to destinationPath do not exist.
static void ClearLabels (Object obj)
Clears all labels of an asset.
static Boolean Copy (Path sourcePath, Path destinationPath, Boolean overwriteExisting=false)
Makes a copy of the source asset and saves it in the destination. Will create destination path folders if necessary.
static Asset Create (Object obj, Path path, Boolean overwriteExisting=false)
Creates (saves) a new asset file at the target path. Also creates all non-existing folders in the path. Defaults to generating a unique filename if there is an existing asset file. Can overwrite existing files, if specified.
static T CreateOrLoad< T > (Path path, Func< Object > getInstance)
Same as: LoadOrCreate <T> (..) - this exists mainly for API discovery reasons. Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
static Boolean Delete (Object obj, Boolean moveToTrash=false)
Deletes the asset. Does nothing if the object is not an asset.
static Boolean Delete (Path path, Boolean moveToTrash=false)
Deletes the asset file. Does nothing if there is no file at the given path.
static Boolean DeleteMany (IEnumerable< Path > paths)
Tries to delete all the given assets.
static Boolean DeleteMany (IEnumerable< String > paths)
Tries to delete all the given assets.
static String[] Find (String filter, String[] searchInFolders=null)
Finds the assets by the given filter criteria. Returns an array of string GUIDs for compatibility reasons.
static GUID[] FindGuids (String filter, String[] searchInFolders=null)
Finds the assets by the given filter criteria. Returns an array of GUID instances.
static Path[] FindPaths (String filter, String[] searchInFolders=null)
Finds the assets by the given filter criteria. Returns an array of asset paths.
static Object ForceSave (Object obj)
Forces the object to be saved to disk by first flagging it as dirty. Note: Be sure that you need to 'force' the save operation, since serializing and object and writing it to disk is a slow operation. Save(UnityEngine.Object)
static String[] GetDependencies (Path path, Boolean recursive=false)
Returns the dependencies of the asset at the given path. Returns paths to dependent assets.
static String[] GetDependencies (Path[] paths, Boolean recursive=false)
Returns the dependencies of the assets at the given paths. Returns paths to dependent assets.
static Texture GetIcon (Path path)
Returns the icon associated with the asset type.
static String[] GetLabels (GUID guid)
Returns an asset's labels.
static String[] GetLabels (Object obj)
Returns an asset's labels.
static String GetLastErrorMessage ()
Returns the last error message returned by some methods that provide such a message, for example Move and Rename. Rename Move
static Int64 GetLocalFileId (Object obj)
Returns the local FileID of the object.
static void Import (Path path, ImportAssetOptions options=ImportAssetOptions.Default)
Imports a file at a given path that was created or modified 'externally', ie not via Asset(Database) methods. For example, any file/folder modified via System.IO.File.Write*() methods or through batch scripts. Note: If the path does not exist, this method does nothing. You will need to call Asset.Database.ImportAll() if you want to get rid of an externally deleted file that still exists in the AssetDatabase.
static void ImportAll (ImportAssetOptions options=ImportAssetOptions.Default)
static Boolean IsForeign (Object obj)
static Boolean IsImported (Object obj)
Checks if the object is an asset in the AssetDatabase. If it isn't but you know the asset file exists then you need to Import() the asset. Unlike AssetDatabase, will not throw a NullRef if you pass null.
static Boolean IsLoaded (Object obj)
Returns whether this object's main asset is loaded.
static Boolean IsLoaded (Path path)
Returns whether this path's main asset is loaded.
static Boolean IsMain (Object obj)
Returns whether this object is the asset's 'main' object.
static Boolean IsNative (Object obj)
Returns whether this is a native asset. Native assets are serialized directly by Unity, such as materials. Note that scenes, prefabs and assembly definitions are considered foreign assets.
static Boolean IsSub (Object obj)
Returns whether this object is a sub-asset of a composite asset. For example an Animation inside an FBX file.
static T Load< T > (GUID guid)
Loads the main asset object for the guid. Commonly this is the only object of the asset, but there are assets that consist of multiple objects such as Mesh assets that may contain for example animations and materials.
static T Load< T > (Path path)
Loads the main asset object at the path. Commonly this is the only object of the asset, but there are assets that consist of multiple objects such as Mesh assets that may contain for example animations and materials.
static T LoadOrCreate< T > (Path path, System.Func< Object > getInstance)
Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
static Type MainType (Path path)
Returns the type of the main asset at the path.
static Boolean Move (Path sourcePath, Path destinationPath)
Moves an asset from source to destination path. Any non-existing folders in destination path will be created.
static void OpenInDefaultApplication (Int32 instanceId, Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset (by its instanceID) in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
static void OpenInDefaultApplication (Object obj, Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
static void OpenInDefaultApplication (Path path, Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset at the path in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
static implicit operator Asset (GUID guid)
Implicit conversion of GUID to an asset instance.
static implicit operator Asset (Object obj)
Implicit conversion of UnityEngine.Object to an asset instance.
static implicit operator Asset (Path path)
Implicit conversion of Asset.Path to an asset instance.
static implicit operator Object (Asset asset)
Implicit conversion to UnityEngine.Object by returning the asset's MainObject.
static Boolean Rename (Path assetPath, String newFileName)
Renames an asset's file or folder name. NOTE: Cannot be used to change a file's extension. Use Move instead. Move
static void Save (GUID guid)
Saves any changes to the object to disk.
static Object Save (Object obj)
Saves the object to disk if it is marked dirty. Note: Depending on how changes were made you may have to use ForceSave(Object) instead. ForceSave(UnityEngine.Object)
static void SaveAll ()
static void SetLabels (Object obj, String[] labels)
Sets an asset's labels.
static Boolean Trash (Object obj)
Moves the asset to the OS trash (same as Delete, but recoverable). Does nothing if the object is not an asset.
static Boolean Trash (Path path)
Moves the asset file to the OS trash (same as Delete, but recoverable). Does nothing if there is no file at the given path.
static Boolean TrashMany (IEnumerable< Path > paths)
Tries to move all the given assets to the OS trash.
static Boolean TrashMany (IEnumerable< String > paths)
Tries to move all the given assets to the OS trash.
Properties
Path AssetPath [get]
Returns the path to the asset (file or folder).
static IList< String > DeleteFailedPaths [get]
The paths that failed to be deleted or trashed. Is an empty list if no failure occured on the last call to DeleteMany or TrashMany.
String[] Dependencies [get]
Returns the assets dependencies recursively. Returns paths to the dependent assets.
GUID Guid [get]
Returns the asset's GUID.
Texture Icon [get]
Returns the icon texture associated with the asset type.
Boolean IsDeleted [get]
Returns true after the asset has been deleted.
Boolean IsForeignAsset [get]
Returns whether this is a foreign asset.
Boolean IsNativeAsset [get]
Returns whether this is a native asset.
String[] Labels [get, set]
Sets or gets the labels associated with the asset.
String LastErrorMessage [get]
Returns the last error message from some file operations that return a Boolean, for example: Move, Rename, Copy.
Int64 LocalFileId [get]
Returns the local FileID of the asset.
Object MainObject [get]
Returns the asset's main object.
Type Type [get]
Returns the type of the main asset.
Constructor & Destructor Documentation
Asset() [1/4]
CodeSmile.Editor.Asset.Asset (Object obj, Path path, Boolean overwriteExisting = false)
Returns an instance by creating (saving) the object as an asset file at the given path. The object must not already be an asset. If it is an asset you must use the ctor without a path.
Parameters
obj The object to create/save as asset file.
path The path to the asset file. It must have a valid asset extension.
overwriteExisting If true, will overwrite any existing asset file at the location. Otherwise may generate a uniquely numbered file name.
Exceptions
ArgumentNullException If the object is null.
ArgumentNullException If the assetPath is null.
ArgumentException If the object already is an asset.
        {
            ThrowIf.ArgumentIsNull(obj, nameof(obj));
            ThrowIf.ArgumentIsNull(path, nameof(path));
            ThrowIf.AlreadyInDatabase(obj);
            Create(obj, path, overwriteExisting);
            SetMainObjectAndAssetPath(obj);
        }
References CodeSmile.Editor.Asset.Create().
Asset() [2/4]
CodeSmile.Editor.Asset.Asset (Path path)
Returns an instance from a path to an existing asset.
Parameters
path
Exceptions
ArgumentNullException If the assetPath is null.
FileNotFoundException If the assetPath does not point to an existing asset file.
Asset() [3/4]
CodeSmile.Editor.Asset.Asset (Object obj)
Returns an instance from an existing asset reference.
Parameters
obj
Exceptions
ArgumentNullException If the object is null.
ArgumentException If the object is not an asset reference.
Asset() [4/4]
CodeSmile.Editor.Asset.Asset (GUID assetGuid)
Returns an instance from an existing asset's GUID.
Parameters
assetGuid
Exceptions
ArgumentException If the GUID is not in the AssetDatabase (not an asset).
Member Function Documentation
AddLabel() [1/2]
static void CodeSmile.Editor.Asset.AddLabel (Object obj, String label) static
Adds a label to an asset's list of labels. Note: this is less efficient than SetLabels. It is provided as a convenience to add a few labels without having to do the conversion to List, then add a label, then ToArray() the list. This is what is done internally.
AddLabels
Parameters
obj
label
        {
            var existingLabels = new List<String>(GetLabels(obj));
            existingLabels.Add(label);
            AssetDatabase.SetLabels(obj, existingLabels.ToArray());
        }
References CodeSmile.Editor.Asset.GetLabels().
AddLabel() [2/2]
void CodeSmile.Editor.Asset.AddLabel (String label)
Adds a label to the asset.
Parameters
label
AddLabels() [1/2]
static void CodeSmile.Editor.Asset.AddLabels (Object obj, String[] labels) static
Adds several labels to an asset's list of labels.
AddLabel
Parameters
obj
labels
        {
            var existingLabels = new List<String>(GetLabels(obj));
            existingLabels.AddRange(labels);
            AssetDatabase.SetLabels(obj, existingLabels.ToArray());
        }
References CodeSmile.Editor.Asset.GetLabels().
AddLabels() [2/2]
void CodeSmile.Editor.Asset.AddLabels (String[] labels)
Adds several labels to the asset.
Parameters
labels
BatchEditing()
static void CodeSmile.Editor.Asset.BatchEditing (Action assetEditingAction, Boolean rethrowExceptions = false) static
Speed up mass asset editing (create, modify, delete, import, etc). Within the callback action, the AssetDatabase does neither import nor auto-refresh assets. This can significantly speed up mass asset editing tasks where you work with individual assets in a loop. Internally calls Start/StopAssetEditing in a try/finally block so that exceptions will not cause the AssetDatabase to remain stopped indefinitely.
See also
https://docs.unity3d.com/Manual/AssetDatabaseBatching.html
Parameters
assetEditingAction
        {
            ThrowIf.ArgumentIsNull(assetEditingAction, nameof(assetEditingAction));
            try
            {
                Database.StartAssetEditing();
                assetEditingAction.Invoke();
            }
            catch (Exception ex)
            {
                Debug.LogError($"Exception during BatchEditing: {ex.Message}");
                if (rethrowExceptions)
                    throw ex; // re-throw to caller
            }
            finally
            {
                Database.StopAssetEditing();
            }
        }
CanMove() [1/2]
Boolean CodeSmile.Editor.Asset.CanMove (Path destinationPath)
Tests if a Move operation will be successful without actually moving the asset. Note: Returns false if any of the folders to destinationPath do not exist.
Parameters
destinationPath The path where to move the asset to. Can have a different extension.
Returns
True if moving the asset will be successful, false otherwise.
CanMove() [2/2]
static Boolean CodeSmile.Editor.Asset.CanMove (Path sourcePath, Path destinationPath) static
Tests if a Move operation will be successful without actually moving the asset. Note: Returns false if any of the folders to destinationPath do not exist.
Parameters
sourcePath The path to an existing asset.
destinationPath The path where to move the asset to. Can have a different extension.
Returns
True if moving the asset will be successful, false otherwise.
        {
            if (sourcePath == null || destinationPath == null || destinationPath.IsValid == false)
                return false;
            return Succeeded(AssetDatabase.ValidateMoveAsset(sourcePath, destinationPath));
        }
References CodeSmile.Editor.Asset.Path.IsValid.
Referenced by CodeSmile.Editor.Asset.Copy().
ClearLabels()
static void CodeSmile.Editor.Asset.ClearLabels (Object obj) static
Clears all labels of an asset.
Parameters
obj
Copy() [1/2]
Asset CodeSmile.Editor.Asset.Copy (Path destinationPath, Boolean overwriteExisting = false)
Makes a copy of the asset. Will create destination path folders if necessary.
Parameters
destinationPath
overwriteExisting
Returns
The Asset instance of the copy, or null if copying failed.
        {
            ThrowIf.AssetDeleted(this);
            // get the expected copy's path first
            var pathToCopy = Path.GetOverwriteOrUnique(destinationPath, overwriteExisting);
            var success = Copy(m_AssetPath, destinationPath);
            return success ? new Asset(pathToCopy) : null;
        }
References CodeSmile.Editor.Asset.Copy().
Copy() [2/2]
static Boolean CodeSmile.Editor.Asset.Copy (Path sourcePath, Path destinationPath, Boolean overwriteExisting = false) static
Makes a copy of the source asset and saves it in the destination. Will create destination path folders if necessary.
Parameters
sourcePath the source asset to copy from
destinationPath the destination path the copy is saved
overwriteExisting True if an existing destination asset should be replaced. False if a unique filename should be generated.
Returns
True if copying succeeded, false if it failed.
        {
            ThrowIf.ArgumentIsNull(sourcePath, nameof(sourcePath));
            ThrowIf.ArgumentIsNull(destinationPath, nameof(destinationPath));
            ThrowIf.AssetPathNotInDatabase(sourcePath);
            ThrowIf.OverwritingSamePath(sourcePath, destinationPath, overwriteExisting);
            var newDestPath = Path.GetOverwriteOrUnique(destinationPath, overwriteExisting);
            if (newDestPath.IsValid == false)
                return false;
            newDestPath.CreateFolders(); // CanMove fails if the path doesn't exist
            if (CanMove(sourcePath, newDestPath) == false) // this provides us with a LastErrorMessage
                return false;
            return AssetDatabase.CopyAsset(sourcePath, newDestPath);
        }
References CodeSmile.Editor.Asset.CanMove(), and CodeSmile.Editor.Asset.Path.CreateFolders().
Referenced by CodeSmile.Editor.Asset.Copy().
Create()
static Asset CodeSmile.Editor.Asset.Create (Object obj, Path path, Boolean overwriteExisting = false) static
Creates (saves) a new asset file at the target path. Also creates all non-existing folders in the path. Defaults to generating a unique filename if there is an existing asset file. Can overwrite existing files, if specified.
Parameters
obj The object to save as an asset file.
path The relative asset path with filename and extension.
overwriteExisting (Default: false) If true, any existing asset file will be overwritten.
Returns
        {
            path.CreateFolders();
            CreateAssetInternal(obj, path, overwriteExisting);
            return new Asset(obj);
        }
References CodeSmile.Editor.Asset.Path.CreateFolders().
Referenced by CodeSmile.Editor.Asset.Asset(), and CodeSmile.Editor.Asset.LoadOrCreate< T >().
CreateOrLoad< T >()
static T CodeSmile.Editor.Asset.CreateOrLoad< T > (Path path, Func< Object > getInstance) static
Same as: LoadOrCreate <T> (..) - this exists mainly for API discovery reasons. Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
Parameters
path
getInstance
Template Parameters
T
Returns
Type Constraints
T : Object
T : LoadOrCreate<T>
T : path
T : getInstance
Delete() [1/3]
Object CodeSmile.Editor.Asset.Delete (Boolean moveToTrash = false)
Deletes the asset. Does not Destroy the object. CAUTION: The asset instance should be discarded afterwards.
Parameters
moveToTrash If true, file will be moved to OS trashcan (recoverable delete).
Returns
If successful, returns the former MainObject - it is still valid but it is no longer an asset. Returns null if the object wasn't deleted.
        {
            var mainObject = m_MainObject;
            if (IsDeleted == false && Delete(m_AssetPath, moveToTrash))
                InvalidateInstance();
            return mainObject;
        }
References CodeSmile.Editor.Asset.Delete(), and CodeSmile.Editor.Asset.IsDeleted.
Delete() [2/3]
static Boolean CodeSmile.Editor.Asset.Delete (Object obj, Boolean moveToTrash = false) static
Deletes the asset. Does nothing if the object is not an asset.
Parameters
moveToTrash If true, file will be moved to OS trashcan (recoverable delete).
path
Delete() [3/3]
static Boolean CodeSmile.Editor.Asset.Delete (Path path, Boolean moveToTrash = false) static
Deletes the asset file. Does nothing if there is no file at the given path.
Parameters
moveToTrash If true, file will be moved to OS trashcan (recoverable delete).
path
        {
            if (path == null || path.Exists == false)
                return false;
            return moveToTrash ? AssetDatabase.MoveAssetToTrash(path) : AssetDatabase.DeleteAsset(path);
        }
References CodeSmile.Editor.Asset.Path.Exists.
Referenced by CodeSmile.Editor.Asset.Delete().
DeleteMany() [1/2]
static Boolean CodeSmile.Editor.Asset.DeleteMany (IEnumerable< Path > paths) static
Tries to delete all the given assets.
Parameters
paths
Returns
True if all assets where deleted, false if one or more failed to delete whose paths you can access via the Asset.Database.DeleteFailedPaths property.
DeleteFailedPaths
DeleteMany() [2/2]
static Boolean CodeSmile.Editor.Asset.DeleteMany (IEnumerable< String > paths) static
Tries to delete all the given assets.
Parameters
paths
Returns
True if all assets where deleted, false if one or more failed to delete whose paths you can access via the Asset.Database.DeleteFailedPaths property.
DeleteFailedPaths
Duplicate()
Asset CodeSmile.Editor.Asset.Duplicate ()
Creates a duplicate of the asset with a new, unique file name.
Returns
The asset instance of the duplicate.
Find()
static String[] CodeSmile.Editor.Asset.Find (String filter, String[] searchInFolders = null) static
Finds the assets by the given filter criteria. Returns an array of string GUIDs for compatibility reasons.
Parameters
filter
searchInFolders
Returns
FindGuids FindPaths
FindGuids()
static GUID[] CodeSmile.Editor.Asset.FindGuids (String filter, String[] searchInFolders = null) static
Finds the assets by the given filter criteria. Returns an array of GUID instances.
Parameters
filter
searchInFolders
Returns
Find FindPaths
FindPaths()
static Path[] CodeSmile.Editor.Asset.FindPaths (String filter, String[] searchInFolders = null) static
Finds the assets by the given filter criteria. Returns an array of asset paths.
Parameters
filter
searchInFolders
Returns
Find FindGuids
ForceSave() [1/2]
void CodeSmile.Editor.Asset.ForceSave ()
Forces the object to be written to disk, whether it is dirty or not. Save()
        {
            ThrowIf.AssetDeleted(this);
            ForceSave(m_MainObject);
        }
References CodeSmile.Editor.Asset.ForceSave().
Referenced by CodeSmile.Editor.Asset.ForceSave().
ForceSave() [2/2]
static Object CodeSmile.Editor.Asset.ForceSave (Object obj) static
Forces the object to be saved to disk by first flagging it as dirty. Note: Be sure that you need to 'force' the save operation, since serializing and object and writing it to disk is a slow operation. Save(UnityEngine.Object)
Parameters
obj returns the object for method chaining
Get< T >()
T CodeSmile.Editor.Asset.Get< T > ()
Returns MainObject cast to T, or null. But recommended usage is:
MyType t = asset as MyType;
Template Parameters
T
Returns
Type Constraints
T : Object
T : m_MainObject
T : as
T : T
GetDependencies() [1/2]
static String[] CodeSmile.Editor.Asset.GetDependencies (Path path, Boolean recursive = false) static
Returns the dependencies of the asset at the given path. Returns paths to dependent assets.
Parameters
path
recursive
Returns
GetDependencies() [2/2]
static String[] CodeSmile.Editor.Asset.GetDependencies (Path[] paths, Boolean recursive = false) static
Returns the dependencies of the assets at the given paths. Returns paths to dependent assets.
Parameters
paths
recursive
Returns
GetIcon()
static Texture CodeSmile.Editor.Asset.GetIcon (Path path) static
Returns the icon associated with the asset type.
Parameters
path
Returns
GetLabels() [1/2]
static String[] CodeSmile.Editor.Asset.GetLabels (GUID guid) static
Returns an asset's labels.
Parameters
guid
Returns
GetLabels() [2/2]
static String[] CodeSmile.Editor.Asset.GetLabels (Object obj) static
Returns an asset's labels.
Parameters
obj
Returns
Referenced by CodeSmile.Editor.Asset.AddLabel(), and CodeSmile.Editor.Asset.AddLabels().
GetLocalFileId()
static Int64 CodeSmile.Editor.Asset.GetLocalFileId (Object obj) static
Returns the local FileID of the object.
Parameters
obj
Returns
The local fileID or 0 on failure.
Import()
static void CodeSmile.Editor.Asset.Import (Path path, ImportAssetOptions options = ImportAssetOptions::Default) static
Imports a file at a given path that was created or modified 'externally', ie not via Asset(Database) methods. For example, any file/folder modified via System.IO.File.Write*() methods or through batch scripts. Note: If the path does not exist, this method does nothing. You will need to call Asset.Database.ImportAll() if you want to get rid of an externally deleted file that still exists in the AssetDatabase.
Parameters
path
options
        {
            if (path != null && path.ExistsInFileSystem)
                AssetDatabase.ImportAsset(path, options);
        }
References CodeSmile.Editor.Asset.Path.ExistsInFileSystem.
ImportAll()
static void CodeSmile.Editor.Asset.ImportAll (ImportAssetOptions options = ImportAssetOptions.Default) static
Formerly known as 'Refresh()', this scans for and imports assets that have been modified externally. External is defined as 'any file modification operation not done through the AssetDatabase', for example by using System.IO methods or by running scripts and other external tools.
Since Refresh() 'traditionally' gets called way too many times needlessly a more descriptive name was chosen to reflect what this method does. I even considered naming it 100% accurately as: ImportExternallyModifiedAndUnloadUnusedAssets()
CAUTION: Calling this may have an adverse effect on editor performance, since it calls Resources.UnloadUnusedAssets internally and it also discards any unsaved objects not marked as 'dirty' that are only referenced by scripts, leading to potential loss of unsaved data. https://docs.unity3d.com/Manual/AssetDatabaseRefreshing.html
Asset.Import(Path, ImportAssetOptions)
Parameters
options
IsForeign()
static Boolean CodeSmile.Editor.Asset.IsForeign (Object obj) static
Returns whether this is a foreign asset.
A foreign asset is any type of file that Unity doesn't use directly but rather maintains cached versions of it in the Library folder. For example, a .png image is a foreign asset, there is no editor inside Unity for it, and the representation of the .png depends on the asset's settings and build platform (eg compression, max size, etc). Other foreign assets: scenes (.unity), prefabs, assembly definitions.
IsNative
Parameters
obj
Returns
IsImported()
static Boolean CodeSmile.Editor.Asset.IsImported (Object obj) static
Checks if the object is an asset in the AssetDatabase. If it isn't but you know the asset file exists then you need to Import() the asset. Unlike AssetDatabase, will not throw a NullRef if you pass null.
Parameters
obj
Returns
Returns false if the object isn't in the database or if the object is null.
IsLoaded() [1/2]
static Boolean CodeSmile.Editor.Asset.IsLoaded (Object obj) static
Returns whether this object's main asset is loaded.
Parameters
obj
Returns
IsLoaded() [2/2]
static Boolean CodeSmile.Editor.Asset.IsLoaded (Path path) static
Returns whether this path's main asset is loaded.
Parameters
path
Returns
IsMain()
static Boolean CodeSmile.Editor.Asset.IsMain (Object obj) static
Returns whether this object is the asset's 'main' object.
Parameters
obj
Returns
IsNative()
static Boolean CodeSmile.Editor.Asset.IsNative (Object obj) static
Returns whether this is a native asset. Native assets are serialized directly by Unity, such as materials. Note that scenes, prefabs and assembly definitions are considered foreign assets.
IsForeign
Parameters
obj
Returns
IsSub()
static Boolean CodeSmile.Editor.Asset.IsSub (Object obj) static
Returns whether this object is a sub-asset of a composite asset. For example an Animation inside an FBX file.
Parameters
obj
Returns
Load< T >() [1/2]
static T CodeSmile.Editor.Asset.Load< T > (GUID guid) static
Loads the main asset object for the guid. Commonly this is the only object of the asset, but there are assets that consist of multiple objects such as Mesh assets that may contain for example animations and materials.
Parameters
guid
Template Parameters
T
Returns
The asset object or null if the guid is not an asset guid.
Type Constraints
T : Object
                                                   : Object
        {
            ThrowIf.NotAnAssetGuid(guid);
            return Load<T>(Path.Get(guid));
        }
References CodeSmile.Editor.Asset.Path.Get().
Load< T >() [2/2]
static T CodeSmile.Editor.Asset.Load< T > (Path path) static
Loads the main asset object at the path. Commonly this is the only object of the asset, but there are assets that consist of multiple objects such as Mesh assets that may contain for example animations and materials.
Parameters
path
Template Parameters
T
Returns
The asset object or null if the path does not exist or the asset is not imported.
Type Constraints
T : Object
                                                   : Object
        {
            ThrowIf.ArgumentIsNull(path, nameof(path));
            ThrowIf.DoesNotExistInFileSystem(path);
            var assetType = MainType(path);
            ThrowIf.AssetNotImported(path, assetType);
            ThrowIf.AssetTypeMismatch<T>(path, assetType);
            var obj = (T)AssetDatabase.LoadMainAssetAtPath(path);
            ThrowIf.AssetLoadReturnedNull(obj, path); // this may not be necessary but just to be sure
            return obj;
        }
References CodeSmile.Editor.Asset.MainType().
LoadOrCreate< T >()
static T CodeSmile.Editor.Asset.LoadOrCreate< T > (Path path, System::Func< Object > getInstance) static
Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
Parameters
path
getInstance
Template Parameters
T
Returns
Type Constraints
T : Object
                                                                                            : Object
        {
            if (path.Exists)
                return Load<T>(path);
            var obj = getInstance.Invoke() as T;
            Create(obj, path);
            return obj;
        }
References CodeSmile.Editor.Asset.Create().
MainType()
static Type CodeSmile.Editor.Asset.MainType (Path path) static
Returns the type of the main asset at the path.
Parameters
path
Returns
the type of the asset or null if the path does not exist
Referenced by CodeSmile.Editor.Asset.Load< T >().
Move() [1/2]
Boolean CodeSmile.Editor.Asset.Move (Path destinationPath)
Moves asset to destination path. Any non-existing folders in destination path will be created. AssetPath property is updated accordingly.
Parameters
sourcePath
destinationPath
Returns
True if the move was successful.
        {
            if (Move(m_AssetPath, destinationPath))
            {
                SetAssetPathFromObject();
                return true;
            }
            return false;
        }
References CodeSmile.Editor.Asset.Move().
Move() [2/2]
static Boolean CodeSmile.Editor.Asset.Move (Path sourcePath, Path destinationPath) static
Moves an asset from source to destination path. Any non-existing folders in destination path will be created.
Parameters
sourcePath
destinationPath
Returns
True if the move was successful.
        {
            if (sourcePath == null || destinationPath == null || destinationPath.IsValid == false)
                return false;
            if (destinationPath.IsValid == false)
                return false;
            destinationPath.CreateFolders();
            return Succeeded(AssetDatabase.MoveAsset(sourcePath, destinationPath));
        }
References CodeSmile.Editor.Asset.Path.CreateFolders(), and CodeSmile.Editor.Asset.Path.IsValid.
Referenced by CodeSmile.Editor.Asset.Move().
OpenInDefaultApplication() [1/4]
static void CodeSmile.Editor.Asset.OpenInDefaultApplication (Int32 instanceId, Int32 lineNumber = -1, Int32 columnNumber = -1) static
Opens the asset (by its instanceID) in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
OpenInDefaultApplication() [2/4]
void CodeSmile.Editor.Asset.OpenInDefaultApplication (Int32 lineNumber = -1, Int32 columnNumber = -1)
Opens the asset in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
OpenInDefaultApplication() [3/4]
static void CodeSmile.Editor.Asset.OpenInDefaultApplication (Object obj, Int32 lineNumber = -1, Int32 columnNumber = -1) static
Opens the asset in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
OpenInDefaultApplication() [4/4]
static void CodeSmile.Editor.Asset.OpenInDefaultApplication (Path path, Int32 lineNumber = -1, Int32 columnNumber = -1) static
Opens the asset at the path in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
operator Asset() [1/3]
static implicit CodeSmile.Editor.Asset.operator Asset (GUID guid) static
Implicit conversion of GUID to an asset instance.
Parameters
guid An asset instance.
Returns
An asset instance or null if guid is empty.
operator Asset() [2/3]
static implicit CodeSmile.Editor.Asset.operator Asset (Object obj) static
Implicit conversion of UnityEngine.Object to an asset instance.
Parameters
obj
Returns
An asset instance or null if obj is null.
operator Asset() [3/3]
static implicit CodeSmile.Editor.Asset.operator Asset (Path path) static
Implicit conversion of Asset.Path to an asset instance.
Parameters
path
Returns
An asset instance or null if path is null.
operator Object()
static implicit CodeSmile.Editor.Asset.operator Object (Asset asset) static
Implicit conversion to UnityEngine.Object by returning the asset's MainObject.
Parameters
asset The main object of the asset.
Rename() [1/2]
static Boolean CodeSmile.Editor.Asset.Rename (Path assetPath, String newFileName) static
Renames an asset's file or folder name. NOTE: Cannot be used to change a file's extension. Use Move instead. Move
Parameters
assetPath The path to the file or folder to rename.
newFileName The new name of the file or folder, without extension. You may pass in a full path, in this case only the file or folder name of that path is used.
Returns
True if the rename succeeded, false otherwise. If false, Asset.LastErrorMessage provides a human-readable failure reason.
        {
            if (assetPath == null || newFileName == null)
                return false;
            // also accept full paths .. because, why not?
            try
            {
                newFileName = System.IO.Path.GetFileName(newFileName); // throws on illegal chars
            }
            catch (Exception e)
            {
                SetLastErrorMessage(e.Message);
                return false;
            }
            return Succeeded(AssetDatabase.RenameAsset(assetPath, newFileName));
        }
Referenced by CodeSmile.Editor.Asset.Rename().
Rename() [2/2]
Boolean CodeSmile.Editor.Asset.Rename (String newFileName)
Renames an asset's file or folder name. NOTE: Cannot be used to change a file's extension. Use Move instead. Move
Parameters
newFileName The new name of the file or folder, without extension. You may pass in a full path, in this case only the file or folder name of that path is used.
Returns
True if the rename succeeded. The AssetPath property will be updated accordingly. If false, Asset.LastErrorMessage provides a human-readable failure reason and the AssetPath property remains unchanged.
        {
            if (Rename(m_AssetPath, newFileName))
            {
                SetAssetPathFromObject();
                return true;
            }
            return false;
        }
References CodeSmile.Editor.Asset.Rename().
Save() [1/3]
void CodeSmile.Editor.Asset.Save ()
Saves any changes to the object to disk if it is marked as dirty. ForceSave()
        {
            ThrowIf.AssetDeleted(this);
            Save(m_MainObject);
        }
References CodeSmile.Editor.Asset.Save().
Referenced by CodeSmile.Editor.Asset.Save().
Save() [2/3]
static void CodeSmile.Editor.Asset.Save (GUID guid) static
Saves any changes to the object to disk.
Parameters
guid
        {
            ThrowIf.NotAnAssetGuid(guid);
            AssetDatabase.SaveAssetIfDirty(guid);
        }
Save() [3/3]
static Object CodeSmile.Editor.Asset.Save (Object obj) static
Saves the object to disk if it is marked dirty. Note: Depending on how changes were made you may have to use ForceSave(Object) instead. ForceSave(UnityEngine.Object)
Parameters
obj returns the object for method chaining
SaveAll()
static void CodeSmile.Editor.Asset.SaveAll () static
Saves all unsaved (dirty) objects.
CAUTION: Consider that the user may NOT want to have unsaved assets 'randomly' saved! If you work with specific object(s) already it is in the user's best interest if you use Asset.Save(obj) instead. Also consider using Asset.BatchEditing(Action) in that case.
Asset.Save(Object) Asset.BatchEditing(System.Action)
SetLabels()
static void CodeSmile.Editor.Asset.SetLabels (Object obj, String[] labels) static
Sets an asset's labels.
Parameters
obj
labels
Trash() [1/3]
Object CodeSmile.Editor.Asset.Trash ()
Moves the asset to the OS trash (same as Delete, but recoverable). Does not Destroy the object. CAUTION: The asset instance should be discarded afterwards.
Returns
If successful, returns the former MainObject - it is still valid but it is no longer an asset. Returns null if the object wasn't trashed.
        {
            var mainObject = m_MainObject;
            if (IsDeleted == false && Trash(m_AssetPath))
                InvalidateInstance();
            return mainObject;
        }
References CodeSmile.Editor.Asset.IsDeleted, and CodeSmile.Editor.Asset.Trash().
Referenced by CodeSmile.Editor.Asset.Trash().
Trash() [2/3]
static Boolean CodeSmile.Editor.Asset.Trash (Object obj) static
Moves the asset to the OS trash (same as Delete, but recoverable). Does nothing if the object is not an asset.
Parameters
obj
Returns
True if successfully trashed
Trash() [3/3]
static Boolean CodeSmile.Editor.Asset.Trash (Path path) static
Moves the asset file to the OS trash (same as Delete, but recoverable). Does nothing if there is no file at the given path.
Parameters
path
Returns
True if successfully trashed
TrashMany() [1/2]
static Boolean CodeSmile.Editor.Asset.TrashMany (IEnumerable< Path > paths) static
Tries to move all the given assets to the OS trash.
Parameters
paths
Returns
True if all assets where trashed, false if one or more failed to trash whose paths you can access via the Asset.Database.DeleteFailedPaths property.
DeleteFailedPaths
TrashMany() [2/2]
static Boolean CodeSmile.Editor.Asset.TrashMany (IEnumerable< String > paths) static
Tries to move all the given assets to the OS trash.
Parameters
paths
Returns
True if all assets where trashed, false if one or more failed to trash whose paths you can access via the Asset.Database.DeleteFailedPaths property.
DeleteFailedPaths
Property Documentation
DeleteFailedPaths
IList<String> CodeSmile.Editor.Asset.DeleteFailedPaths static get
The paths that failed to be deleted or trashed. Is an empty list if no failure occured on the last call to DeleteMany or TrashMany.
Returns
TrashMany(System.Collections.Generic.IEnumerable<CodeSmile.Editor.Asset.Path>) DeleteMany(System.Collections.Generic.IEnumerable<CodeSmile.Editor.Asset.Path>)
IsDeleted
Boolean CodeSmile.Editor.Asset.IsDeleted get
Returns true after the asset has been deleted.
Delete(CodeSmile.Editor.Asset.Path) - Trash(CodeSmile.Editor.Asset.Path)
Referenced by CodeSmile.Editor.Asset.Delete(), and CodeSmile.Editor.Asset.Trash().
IsForeignAsset
Boolean CodeSmile.Editor.Asset.IsForeignAsset get
Returns whether this is a foreign asset.
IsForeign IsNative
Returns
IsNativeAsset
Boolean CodeSmile.Editor.Asset.IsNativeAsset get
Returns whether this is a native asset.
IsNative IsForeign
Returns
Labels
String [] CodeSmile.Editor.Asset.Labels get set
Sets or gets the labels associated with the asset.
        {
            get => GetLabels(m_MainObject);
            set => SetLabels(m_MainObject, value);
        }
The documentation for this class was generated from the following files:
Editor/Asset.BatchEditing.cs
Editor/Asset.cs
Editor/Asset.Delete.cs
Editor/Asset.Copy.cs
Editor/Asset.Create.cs
Editor/Asset.Ctor.cs
Editor/Asset.Find.cs
Editor/Asset.Import.cs
Editor/Asset.Labels.cs
Editor/Asset.Load.cs
Editor/Asset.Move.cs
Editor/Asset.Open.cs
Editor/Asset.Rename.cs
Editor/Asset.Save.cs