de.codesmile.editor.assetdatabase: CodeSmile.Editor.Asset.File Class Reference
CodeSmile.Editor.Asset.File Class Reference
Groups file related operations.
Static Public Member Functions
static void BatchEditing (Action massAssetFileEditAction, Boolean rethrowExceptions=false)
Speed up mass asset editing (create, modify, delete, import, etc). Within the callback action, the AssetDatabase does neither import nor auto-refresh assets. This can significantly speed up mass asset editing tasks where you work with individual assets in a loop. Internally calls Start/StopAssetEditing in a try/finally block so that exceptions will not cause the AssetDatabase to remain stopped indefinitely.
static Boolean CanMove (Path sourcePath, Path destinationPath)
Tests if a Move operation will be successful without actually moving the asset. Note: Returns false if any of the folders to destinationPath do not exist.
static Boolean CanOpenInEditor (Int32 instanceId)
Returns true if the given object can be opened (edited) by the Unity editor.
static Boolean CanOpenInEditor (Object obj)
Returns true if the given object can be opened (edited) by the Unity editor.
static Boolean Copy (Path sourcePath, Path destinationPath, Boolean overwriteExisting=false)
Makes a copy of the source asset and saves it in the destination. Will create destination path folders if necessary.
static Asset Create (Object obj, Path path, Boolean overwriteExisting=false)
Creates (saves) a new asset file at the target path. Also creates all non-existing folders in the path. Defaults to generating a unique filename if there is an existing asset file. Can overwrite existing files, if specified.
static T CreateOrLoad< T > (Path path, Func< Object > getInstance)
Same as: LoadOrCreate <T> (..) - this exists mainly for API discovery reasons. Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
static Boolean Delete (IEnumerable< Path > paths)
Tries to delete all the given assets.
static Boolean Delete (IEnumerable< String > paths)
Tries to delete all the given assets.
static Boolean Delete (Object obj)
Deletes the asset. Does nothing if the object is not an asset.
static Boolean Delete (Path path)
Deletes the asset file. Does nothing if there is no file at the given path.
static String[] Find (String filter, String[] searchInFolders=null)
Finds the assets by the given filter criteria. Returns an array of string GUIDs for compatibility reasons.
static GUID[] FindGuids (String filter, String[] searchInFolders=null)
Finds the assets by the given filter criteria. Returns an array of GUID instances.
static Path[] FindPaths (String filter, String[] searchInFolders=null)
Finds the assets by the given filter criteria. Returns an array of asset paths.
static void ForceSave (Object obj)
Forces the object to be saved to disk by first flagging it as dirty. Note: Be sure that you need to 'force' the save operation, since serializing and object and writing it to disk is a slow operation.
static void Import (Path path, ImportAssetOptions options=ImportAssetOptions.Default)
Imports a file at a given path that was created or modified 'externally', ie not via Asset(Database) methods. For example, any file/folder modified via System.IO.File.Write*() methods or through batch scripts. Note: If the path does not exist, this method does nothing. You will need to call Asset.Database.ImportAll() if you want to get rid of an externally deleted file that still exists in the AssetDatabase.
static T Load< T > (Path path)
Loads the first visible object of the given type from the asset at path. This usually is the main object but it could be any other visible sub-object, depending on the type.
static AssetDatabaseLoadOperation LoadAsync (Path path, Int64 localFileId)
Loads an object and its dependencies asynchronously.
static T LoadMain< T > (GUID guid)
Loads the main asset object for the guid. Commonly this is the only object of the asset, but there are assets that consist of multiple objects such as Mesh assets that may contain for example animations and materials.
static T LoadMain< T > (Path path)
Loads the main asset object at the path. Commonly this is the only object of the asset, but there are assets that consist of multiple objects. For example Mesh assets often contain sub objects like animations and materials.
static T LoadOrCreate< T > (Path path, Func< Object > getInstance)
Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
static Boolean Move (Path sourcePath, Path destinationPath)
Moves an asset from source to destination path. Any non-existing folders in destination path will be created.
static void OpenExternal (Int32 instanceId, Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset (by its instanceID) in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
static void OpenExternal (Object obj, Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
static void OpenExternal (Path path, Int32 lineNumber=-1, Int32 columnNumber=-1)
Opens the asset at the path in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
static Boolean Rename (Path assetPath, String newFileName)
Renames an asset's file or folder name. NOTE: Cannot be used to change a file's extension. Use Move instead. Move
static void Save (GUID guid)
Saves any changes to the object to disk.
static void Save (Object obj)
Saves the object to disk if it is marked dirty. Note: Depending on how changes were made you may have to use ForceSave(Object) instead.
static Boolean Trash (IEnumerable< Path > paths)
Tries to move all the given assets to the OS trash.
static Boolean Trash (IEnumerable< String > paths)
Tries to move all the given assets to the OS trash.
static Boolean Trash (Object obj)
Moves the asset to the OS trash (same as Delete, but recoverable). Does nothing if the object is not an asset.
static Boolean Trash (Path path)
Moves the asset file to the OS trash (same as Delete, but recoverable). Does nothing if there is no file at the given path.
Properties
static IList< String > FailedToDeletePaths [get]
The paths that failed to be deleted or trashed. Is an empty list if no failure occured on the last call to DeleteMany or TrashMany.
Detailed Description
Groups file related operations.
Member Function Documentation
BatchEditing()
static void CodeSmile.Editor.Asset.File.BatchEditing (Action massAssetFileEditAction, Boolean rethrowExceptions = false) static
Speed up mass asset editing (create, modify, delete, import, etc). Within the callback action, the AssetDatabase does neither import nor auto-refresh assets. This can significantly speed up mass asset editing tasks where you work with individual assets in a loop. Internally calls Start/StopAssetEditing in a try/finally block so that exceptions will not cause the AssetDatabase to remain stopped indefinitely.
Parameters
massAssetFileEditAction
            {
                ThrowIf.ArgumentIsNull(massAssetFileEditAction, nameof(massAssetFileEditAction));
                try
                {
                    Database.StartAssetEditing();
                    massAssetFileEditAction.Invoke();
                }
                catch (Exception ex)
                {
                    Debug.LogError($"Exception during BatchEditing: {ex.Message}");
                    if (rethrowExceptions)
                        throw ex; // re-throw to caller
                }
                finally
                {
                    Database.StopAssetEditing();
                }
            }
CanMove()
static Boolean CodeSmile.Editor.Asset.File.CanMove (Path sourcePath, Path destinationPath) static
Tests if a Move operation will be successful without actually moving the asset. Note: Returns false if any of the folders to destinationPath do not exist.
Parameters
sourcePath The path to an existing asset.
destinationPath The path where to move the asset to. Can have a different extension.
Returns
True if moving the asset will be successful, false otherwise.
            {
                if (sourcePath == null || destinationPath == null)
                    return false;
                return Succeeded(AssetDatabase.ValidateMoveAsset(sourcePath, destinationPath));
            }
Referenced by CodeSmile.Editor.Asset.CanMove().
CanOpenInEditor() [1/2]
static Boolean CodeSmile.Editor.Asset.File.CanOpenInEditor (Int32 instanceId) static
Returns true if the given object can be opened (edited) by the Unity editor.
Parameters
instanceId
Returns
CanOpenInEditor() [2/2]
static Boolean CodeSmile.Editor.Asset.File.CanOpenInEditor (Object obj) static
Returns true if the given object can be opened (edited) by the Unity editor.
Parameters
obj
Returns
            {
                ThrowIf.ArgumentIsNull(obj, nameof(obj));
                return CanOpenInEditor(obj.GetInstanceID());
            }
References CodeSmile.Editor.Asset.CanOpenInEditor().
Copy()
static Boolean CodeSmile.Editor.Asset.File.Copy (Path sourcePath, Path destinationPath, Boolean overwriteExisting = false) static
Makes a copy of the source asset and saves it in the destination. Will create destination path folders if necessary.
Parameters
sourcePath the source asset to copy from
destinationPath the destination path the copy is saved
overwriteExisting True if an existing destination asset should be replaced. False if a unique filename should be generated.
Returns
True if copying succeeded, false if it failed.
            {
                ThrowIf.ArgumentIsNull(sourcePath, nameof(sourcePath));
                ThrowIf.ArgumentIsNull(destinationPath, nameof(destinationPath));
                ThrowIf.AssetPathNotInDatabase(sourcePath);
                ThrowIf.OverwritingSamePath(sourcePath, destinationPath, overwriteExisting);
                var newDestPath = Path.GetOverwriteOrUnique(destinationPath, overwriteExisting);
                newDestPath.CreateFolders();
                var success = AssetDatabase.CopyAsset(sourcePath, newDestPath);
                SetLastErrorMessage(success ? String.Empty : $"failed to copy {sourcePath} to {newDestPath}");
                return success;
            }
References CodeSmile.Editor.Asset.Path.CreateFolders().
Referenced by CodeSmile.Editor.Asset.Copy().
Create()
static Asset CodeSmile.Editor.Asset.File.Create (Object obj, Path path, Boolean overwriteExisting = false) static
Creates (saves) a new asset file at the target path. Also creates all non-existing folders in the path. Defaults to generating a unique filename if there is an existing asset file. Can overwrite existing files, if specified.
Parameters
obj The object to save as an asset file.
path The relative asset path with filename and extension.
overwriteExisting (Default: false) If true, any existing asset file will be overwritten.
Returns
            {
                path.CreateFolders();
                CreateAssetInternal(obj, path, overwriteExisting);
                return new Asset(obj);
            }
References CodeSmile.Editor.Asset.Path.CreateFolders().
Referenced by CodeSmile.Editor.Asset.Asset(), and CodeSmile.Editor.Asset.File.LoadOrCreate< T >().
CreateOrLoad< T >()
static T CodeSmile.Editor.Asset.File.CreateOrLoad< T > (Path path, Func< Object > getInstance) static
Same as: LoadOrCreate <T> (..) - this exists mainly for API discovery reasons. Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
Parameters
path
getInstance
Template Parameters
T
Returns
Type Constraints
T : Object
T : LoadOrCreate<T>
T : path
T : getInstance
Delete() [1/4]
static Boolean CodeSmile.Editor.Asset.File.Delete (IEnumerable< Path > paths) static
Tries to delete all the given assets.
Parameters
paths
Returns
True if all assets where deleted, false if one or more failed to delete whose paths you can access via the Asset.Database.DeleteFailedPaths property.
FailedToDeletePaths
Delete() [2/4]
static Boolean CodeSmile.Editor.Asset.File.Delete (IEnumerable< String > paths) static
Tries to delete all the given assets.
Parameters
paths
Returns
True if all assets where deleted, false if one or more failed to delete whose paths you can access via the Asset.Database.DeleteFailedPaths property.
FailedToDeletePaths
Delete() [3/4]
static Boolean CodeSmile.Editor.Asset.File.Delete (Object obj) static
Deletes the asset. Does nothing if the object is not an asset.
Parameters
path
Delete() [4/4]
static Boolean CodeSmile.Editor.Asset.File.Delete (Path path) static
Deletes the asset file. Does nothing if there is no file at the given path.
Parameters
path
            {
                if (path == null || path.Exists == false)
                    return false;
                return AssetDatabase.DeleteAsset(path);
            }
References CodeSmile.Editor.Asset.Path.Exists.
Referenced by CodeSmile.Editor.Asset.Delete().
Find()
static String[] CodeSmile.Editor.Asset.File.Find (String filter, String[] searchInFolders = null) static
Finds the assets by the given filter criteria. Returns an array of string GUIDs for compatibility reasons.
Parameters
filter
searchInFolders
Returns
FindGuids FindPaths
FindGuids()
static GUID[] CodeSmile.Editor.Asset.File.FindGuids (String filter, String[] searchInFolders = null) static
Finds the assets by the given filter criteria. Returns an array of GUID instances.
Parameters
filter
searchInFolders
Returns
Find FindPaths
FindPaths()
static Path[] CodeSmile.Editor.Asset.File.FindPaths (String filter, String[] searchInFolders = null) static
Finds the assets by the given filter criteria. Returns an array of asset paths.
Parameters
filter
searchInFolders
Returns
Find FindGuids
ForceSave()
static void CodeSmile.Editor.Asset.File.ForceSave (Object obj) static
Forces the object to be saved to disk by first flagging it as dirty. Note: Be sure that you need to 'force' the save operation, since serializing and object and writing it to disk is a slow operation.
Parameters
obj the asset object to save
Save(UnityEngine.Object)
Referenced by CodeSmile.Editor.Asset.ForceSave().
Import()
static void CodeSmile.Editor.Asset.File.Import (Path path, ImportAssetOptions options = ImportAssetOptions::Default) static
Imports a file at a given path that was created or modified 'externally', ie not via Asset(Database) methods. For example, any file/folder modified via System.IO.File.Write*() methods or through batch scripts. Note: If the path does not exist, this method does nothing. You will need to call Asset.Database.ImportAll() if you want to get rid of an externally deleted file that still exists in the AssetDatabase.
Parameters
path
options
            {
                if (path != null && path.ExistsInFileSystem)
                    AssetDatabase.ImportAsset(path, options);
            }
References CodeSmile.Editor.Asset.Path.ExistsInFileSystem.
Referenced by CodeSmile.Editor.Asset.SubAsset.SetMain().
Load< T >()
static T CodeSmile.Editor.Asset.File.Load< T > (Path path) static
Loads the first visible object of the given type from the asset at path. This usually is the main object but it could be any other visible sub-object, depending on the type.
LoadMain<T>(CodeSmile.Editor.Asset.Path)
Parameters
path
Template Parameters
T
Returns
Type Constraints
T : Object
T : AssetDatabase.LoadAssetAtPath<T>
T : path
LoadAsync()
static AssetDatabaseLoadOperation CodeSmile.Editor.Asset.File.LoadAsync (Path path, Int64 localFileId) static
Loads an object and its dependencies asynchronously.
Parameters
path
localFileId
Returns
An AssetDatabaseLoadOperation instance to track progress.
LoadMain< T >() [1/2]
static T CodeSmile.Editor.Asset.File.LoadMain< T > (GUID guid) static
Loads the main asset object for the guid. Commonly this is the only object of the asset, but there are assets that consist of multiple objects such as Mesh assets that may contain for example animations and materials.
Parameters
guid
Template Parameters
T
Returns
The asset object or null if the guid is not an asset guid.
Type Constraints
T : Object
                                                           : Object
            {
                ThrowIf.NotAnAssetGuid(guid);
                return LoadMain<T>(Path.Get(guid));
            }
References CodeSmile.Editor.Asset.Path.Get().
LoadMain< T >() [2/2]
static T CodeSmile.Editor.Asset.File.LoadMain< T > (Path path) static
Loads the main asset object at the path. Commonly this is the only object of the asset, but there are assets that consist of multiple objects. For example Mesh assets often contain sub objects like animations and materials.
Load<T>(CodeSmile.Editor.Asset.Path)
Parameters
path
Template Parameters
T
Returns
The asset object or null if the path does not exist or the asset is not imported.
Type Constraints
T : Object
                                                           : Object
            {
                ThrowIf.ArgumentIsNull(path, nameof(path));
                ThrowIf.DoesNotExistInFileSystem(path);
                return AssetDatabase.LoadMainAssetAtPath(path) as T;
            }
LoadOrCreate< T >()
static T CodeSmile.Editor.Asset.File.LoadOrCreate< T > (Path path, Func< Object > getInstance) static
Tries to load the object at path. If it cannot be loaded, it will be created using the Object instance returned by the getObjectInstance Func callback.
Parameters
path
getInstance
Template Parameters
T
Returns
Type Constraints
T : Object
                                                                                         : Object
            {
                if (path.Exists)
                    return LoadMain<T>(path);
                var obj = getInstance.Invoke() as T;
                Create(obj, path);
                return obj;
            }
References CodeSmile.Editor.Asset.File.Create().
Move()
static Boolean CodeSmile.Editor.Asset.File.Move (Path sourcePath, Path destinationPath) static
Moves an asset from source to destination path. Any non-existing folders in destination path will be created.
Parameters
sourcePath
destinationPath
Returns
True if the move was successful.
            {
                if (sourcePath == null || destinationPath == null)
                    return false;
                destinationPath.CreateFolders();
                return Succeeded(AssetDatabase.MoveAsset(sourcePath, destinationPath));
            }
References CodeSmile.Editor.Asset.Path.CreateFolders().
Referenced by CodeSmile.Editor.Asset.Move().
OpenExternal() [1/3]
static void CodeSmile.Editor.Asset.File.OpenExternal (Int32 instanceId, Int32 lineNumber = -1, Int32 columnNumber = -1) static
Opens the asset (by its instanceID) in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
OpenExternal() [2/3]
static void CodeSmile.Editor.Asset.File.OpenExternal (Object obj, Int32 lineNumber = -1, Int32 columnNumber = -1) static
Opens the asset in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
Referenced by CodeSmile.Editor.Asset.OpenExternal().
OpenExternal() [3/3]
static void CodeSmile.Editor.Asset.File.OpenExternal (Path path, Int32 lineNumber = -1, Int32 columnNumber = -1) static
Opens the asset at the path in the default (associated) application. Optional line and column numbers can be specified for text files and applications that support this.
Parameters
obj
lineNumber
columnNumber
Rename()
static Boolean CodeSmile.Editor.Asset.File.Rename (Path assetPath, String newFileName) static
Renames an asset's file or folder name. NOTE: Cannot be used to change a file's extension. Use Move instead. Move
Parameters
assetPath The path to the file or folder to rename.
newFileName The new name of the file or folder, without extension.
Returns
True if the rename succeeded, false otherwise. If false, Asset.LastErrorMessage provides a human-readable failure reason.
            {
                if (assetPath == null || newFileName == null)
                    return false;
                return Succeeded(AssetDatabase.RenameAsset(assetPath, newFileName));
            }
Referenced by CodeSmile.Editor.Asset.Rename().
Save() [1/2]
static void CodeSmile.Editor.Asset.File.Save (GUID guid) static
Saves any changes to the object to disk.
Parameters
guid
            {
                ThrowIf.NotAnAssetGuid(guid);
                AssetDatabase.SaveAssetIfDirty(guid);
            }
Save() [2/2]
static void CodeSmile.Editor.Asset.File.Save (Object obj) static
Saves the object to disk if it is marked dirty. Note: Depending on how changes were made you may have to use ForceSave(Object) instead.
Parameters
obj the asset object to save
ForceSave(UnityEngine.Object)
Referenced by CodeSmile.Editor.Asset.Save().
Trash() [1/4]
static Boolean CodeSmile.Editor.Asset.File.Trash (IEnumerable< Path > paths) static
Tries to move all the given assets to the OS trash.
Parameters
paths
Returns
True if all assets where trashed, false if one or more failed to trash whose paths you can access via the Asset.Database.DeleteFailedPaths property.
File.FailedToDeletePaths
Trash() [2/4]
static Boolean CodeSmile.Editor.Asset.File.Trash (IEnumerable< String > paths) static
Tries to move all the given assets to the OS trash.
Parameters
paths
Returns
True if all assets where trashed, false if one or more failed to trash whose paths you can access via the Asset.Database.DeleteFailedPaths property.
File.FailedToDeletePaths
Trash() [3/4]
static Boolean CodeSmile.Editor.Asset.File.Trash (Object obj) static
Moves the asset to the OS trash (same as Delete, but recoverable). Does nothing if the object is not an asset.
Parameters
obj
Returns
True if successfully trashed
Trash() [4/4]
static Boolean CodeSmile.Editor.Asset.File.Trash (Path path) static
Moves the asset file to the OS trash (same as Delete, but recoverable). Does nothing if there is no file at the given path.
Parameters
path
Returns
True if successfully trashed
Referenced by CodeSmile.Editor.Asset.Trash().
Property Documentation
FailedToDeletePaths
IList<String> CodeSmile.Editor.Asset.File.FailedToDeletePaths static get
The paths that failed to be deleted or trashed. Is an empty list if no failure occured on the last call to DeleteMany or TrashMany.
Returns
Trash(System.Collections.Generic.IEnumerable<CodeSmile.Editor.Asset.Path>) Delete(System.Collections.Generic.IEnumerable<CodeSmile.Editor.Asset.Path>)
The documentation for this class was generated from the following file:
Editor/Asset.File.cs