de.codesmile.editor.assetdatabase: CodeSmile.Editor.Asset.Path.CreateFolders
CreateFolders() [2/2]
static GUID CodeSmile.Editor.Asset.Path.CreateFolders (Path path) static
Creates the folders in the path recursively. Path may point to a file, but only folders will be created.
Parameters
path path to a file or folder
Returns
the GUID of the deepest folder in the hierarchy
            {
                ThrowIf.ArgumentIsNull(path, nameof(path));
                ThrowIf.PathIsNotValid(path);
                var folderPath = path.FolderPathAssumptive;
                if (FileExists(path) || FolderExists(folderPath))
                    return folderPath.Guid;
                var folderNames = ((String)folderPath).Split(new[] { '/' });
                var folderGuid = GuidForExistingPath(folderNames[0]); // first is "Assets"
                var partialPath = folderNames[0];
                for (var i = 1; i < folderNames.Length; i++)
                {
                    partialPath += $"/{folderNames[i]}";
                    if (FolderExists(partialPath))
                    {
                        folderGuid = GuidForExistingPath(partialPath);
                        continue;
                    }
                    var guidString = AssetDatabase.CreateFolder(Get(folderGuid), folderNames[i]);
                    folderGuid = new GUID(guidString);
                }
                return folderGuid;
            }
References CodeSmile.Editor.Asset.Path.FileExists(), CodeSmile.Editor.Asset.Path.FolderExists(), CodeSmile.Editor.Asset.Path.FolderPathAssumptive, CodeSmile.Editor.Asset.Path.Get(), and CodeSmile.Editor.Asset.Path.Guid.
Referenced by CodeSmile.Editor.Asset.File.Copy(), CodeSmile.Editor.Asset.File.Create(), and CodeSmile.Editor.Asset.File.Move().