de.codesmile.editor.assetdatabase: Asset.Path Class Reference
Asset.Path Class Reference
Represents a relative path to an asset file or folder, typically under 'Assets' or 'Packages'. Implicitly converts to/from string. Guards against inconsistencies, eg invalid paths, illegal characters, etc. Provides quick access to File I/O tasks such as getting a file's folder, extension, full path, existance, etc.
Public Member Functions
Path (String directory, String fileName, String extension=DefaultExtension)
Creates an asset path from either a full or relative path to a directory, a filename, and an optional extension (default: 'asset').
Path (String fullOrRelativePath)
Creates an asset path from either a full or relative path. Example input path: "C:\Users\Urso Clever\Untiy Projects\First Projcet\Assets\something" Resulting AssetPath: "Assets/something".
GUID CreateFolders ()
Creates the folders in the path recursively. Path may point to a file but only folders will be created.
override Boolean Equals (Object obj)
Tests path for equality with an object. If the object is a Path or String will use the respective Equals method for these types. In all other cases returns false.
Boolean Equals (Path other)
Tests another path for equality. They are equal if their internal relative path strings are equal.
Boolean Equals (String other)
Tests paths for equality with a string. The string is elevated to a Path instance, and then their internal path strings are compared.
override Int32 GetHashCode ()
Returns the internal path string's hash code.
void OpenFolder ()
Opens the folder externally, for example File Explorer (Windows) or Finder (Mac).
Boolean Rename (String newFileOrFolderName)
Renames the file or folder with a new name.
override String ToString ()
Returns the relative path as string. Same as implicit string conversion.
Static Public Member Functions
static GUID CreateFolders (Path path)
Creates the folders in the path recursively. Path may point to a file, but only folders will be created. If the last path chunk has an extension, it is considered a file.
static Boolean FileExists (Path path)
Tests if the given file exists.
static Boolean FolderExists (Path path)
Returns true if the folder exists. False otherwise, or if the path is to a file.
static Path FromMeta (Path path)
Returns the asset's file path from its .meta file path.
static Path Get (GUID guid)
Gets the path of an asset file.
static Path Get (Object obj)
Gets the path of an asset file.
static GUID GetGuid (Path path, AssetPathToGUIDOptions options=AssetPathToGUIDOptions.IncludeRecentlyDeletedAssets)
Returns the GUID for the path. Returns an empty GUID if the asset at the path does not exist in the database. Exists ExistsInFileSystem
static Path GetScene (Object obj)
Returns the scene's path if the object is instantiated in a scene, otherwise returns the object's path.
static String[] GetSubFolders (Path path)
Returns the names of all subfolders in the path. Returns an empty array of the path points to a file.
static Boolean IsValid (String path)
Returns true if the provided path is valid. This means it contains no illegal folder or file name characters and it isn't too long. If this returns false, Asset.GetLastErrorMessage() contains more detailed information. Asset.GetLastErrorMessage()
static implicit operator Path (String path)
Implicit conversion of an AssetPath instance from a string path (full or relative).
static implicit operator String (Path path)
Implicit conversion to string (relative asset path). Same as ToString().
static Boolean operator!= (Object other, Path path)
Tests for inequality with an object.
static Boolean operator!= (Path path, Object other)
Tests for inequality with an object.
static Boolean operator!= (Path path, Path path2)
Tests two path instances for inequality.
static Boolean operator== (Object other, Path path)
Tests for equality with an object.
static Boolean operator== (Path path, Object other)
Tests for equality with an object.
static Boolean operator== (Path path, Path path2)
Tests two path instances for equality.
static String[] ToAssetPaths (Object[] objects)
Converts an array of objects to their asset paths. The returned array has the same size. Note that some items may be null if the input was null or not an asset.
static Path ToMeta (Path path)
Returns the .meta file path from a path to an asset.
static String[] ToStrings (IEnumerable< Path > paths)
Converts a collection of Path instances to a string array.
static Path UniquifyFilename (Path path)
Returns the path either unaltered or with a numbering to make the file unique. This is only done if an asset file exists at the path. It does not alter folder paths. See also: Project Settings => Editor => Numbering Scheme Note: 'Uniquify' is a proper english verb, it means "to make unique".
Properties
Path AssetPath [get]
Returns the path to the asset file if the path represents a .meta file.
Boolean Exists [get]
Returns true if the path exists in the AssetDatabase. NOTE: This may still return true for asset files that have been deleted externally. ExistsInFileSystem
Boolean ExistsInFileSystem [get]
Returns true if the path exists in the file system, be it file or folder. Returns false if the path does not exist. NOTE: This solely checks for physical existance, a new asset at that path may still not 'exist' in the database until it has been imported. Exists
String Extension [get]
Returns the extension of the file path.
String FileName [get]
Returns the file name with extension.
String FileNameWithoutExtension [get]
Returns the file name without extension.
Path FolderPath [get]
Returns the relative path to the directory the file or folder is in. This means for folders it returns the parent folder.
static String FullAssetsPath [get]
Returns the path to the project's 'Assets' subfolder.
static String FullPackagesPath [get]
Returns the path to the project's 'Packages' subfolder.
String FullPath [get]
Creates and returns the full path, with forward slashes as separators.
static String FullProjectPath [get]
Returns the path to the project's root folder.
GUID Guid [get]
Returns the GUID for the path. Returns an empty GUID if the asset at the path does not exist in the database. Exists ExistsInFileSystem
Path MetaPath [get]
Returns the path to the .meta file if the path represents an asset file.
String[] SubFolders [get]
Returns the names of all subfolders in the current directory. If the path points to a file it returns an empty array, use "path.FolderPath.SubFolders" in this case.
Path UniqueFilePath [get]
Returns the path either unaltered or with a numbering to make the file unique if an asset file already exists at the path. Does not alter path if it does not exist or points to a folder. See also: Project Settings => Editor => Numbering Scheme.
Detailed Description
Represents a relative path to an asset file or folder, typically under 'Assets' or 'Packages'. Implicitly converts to/from string. Guards against inconsistencies, eg invalid paths, illegal characters, etc. Provides quick access to File I/O tasks such as getting a file's folder, extension, full path, existance, etc.
Constructor & Destructor Documentation
Path() [1/2]
Path (String fullOrRelativePath)
Creates an asset path from either a full or relative path. Example input path: "C:\Users\Urso Clever\Untiy Projects\First Projcet\Assets\something" Resulting AssetPath: "Assets/something".
Parameters
fullOrRelativePath Absolute path to project's root folder or a subfolder.
Exceptions
ArgumentException If path does not start with the project's Assets path (Application.dataPath).
            {
                ThrowIf.NullOrWhitespace(fullOrRelativePath, nameof(fullOrRelativePath));
                m_RelativePath = ToRelative(fullOrRelativePath.ToForwardSlashes());
            }
Path() [2/2]
Path (String directory, String fileName, String extension = DefaultExtension)
Creates an asset path from either a full or relative path to a directory, a filename, and an optional extension (default: 'asset').
Example parameters: "\Assets\Some/Sub\Dir", "New File", "MyExt"
Resulting path: "Assets/Some/Sub/Dir/New File.myext"
Parameters
directory Path to a directory under Assets, or just 'Assets'. Can be a relative or absolute path. Leading/trailing path separators are trimmed.
fileName Name of the file without extension. Must not contain path separators.
extension Extension of the file (default: 'asset'). Leading dots will be trimmed. Extension will be lowercase.
Exceptions
ArgumentException
            {
                ThrowIf.NullOrWhitespace(directory, nameof(directory));
                ThrowIf.NullOrWhitespace(fileName, nameof(fileName));
                ThrowIf.NullOrWhitespace(extension, nameof(extension));
                ThrowIf.ContainsPathSeparators(fileName, nameof(fileName));
                var relativeDir = ToRelative(directory.ToForwardSlashes());
                m_RelativePath = $"{relativeDir}/{fileName}.{extension.TrimStart('.').ToLower()}";
            }
Member Function Documentation
CreateFolders() [1/2]
GUID CreateFolders ()
Creates the folders in the path recursively. Path may point to a file but only folders will be created.
Returns
the GUID of the deepest folder in the hierarchy
CreateFolders() [2/2]
static GUID CreateFolders (Path path) static
Creates the folders in the path recursively. Path may point to a file, but only folders will be created. If the last path chunk has an extension, it is considered a file.
Parameters
path path to a file or folder
Returns
the GUID of the deepest folder in the hierarchy
            {
                ThrowIf.ArgumentIsNull(path, nameof(path));
                ThrowIf.PathIsNotValid(path);
                if (FileExists(path))
                    return path.FolderPath.Guid;
                // if the last part has an extension we assume the path points to a file
                var isPresumablyFilePath = String.IsNullOrEmpty(path.Extension) == false;
                var folderPath = isPresumablyFilePath ? path.FolderPath : path;
                if (FolderExists(folderPath))
                    return folderPath.Guid;
                var folderNames = ((String)folderPath).Split(new[] { '/' });
                var folderGuid = GuidForExistingPath(folderNames[0]); // first is "Assets"
                var partialPath = folderNames[0];
                for (var i = 1; i < folderNames.Length; i++)
                {
                    partialPath += $"/{folderNames[i]}";
                    if (FolderExists(partialPath))
                    {
                        folderGuid = GuidForExistingPath(partialPath);
                        continue;
                    }
                    folderGuid = CreateSubFolder(Get(folderGuid), folderNames[i]);
                }
                return folderGuid;
            }
References Asset.Path.Extension, Asset.Path.FileExists(), Asset.Path.FolderExists(), Asset.Path.FolderPath, Asset.Path.Get(), and Asset.Path.Guid.
Referenced by Asset.File.Copy(), Asset.File.Create(), and Asset.File.Move().
Equals() [1/3]
override Boolean Equals (Object obj)
Tests path for equality with an object. If the object is a Path or String will use the respective Equals method for these types. In all other cases returns false.
Parameters
obj
Returns
            {
                if (obj is Path path)
                    return Equals(path);
                if (obj is String str)
                    return Equals(str);
                return false;
            }
References Asset.Path.Equals().
Equals() [2/3]
Boolean Equals (Path other)
Tests another path for equality. They are equal if their internal relative path strings are equal.
Parameters
other
Returns
            {
                if (ReferenceEquals(other, null))
                    return false;
                if (ReferenceEquals(this, other))
                    return true;
                return m_RelativePath.Equals(other.m_RelativePath);
            }
Referenced by Asset.Path.Equals().
Equals() [3/3]
Boolean Equals (String other)
Tests paths for equality with a string. The string is elevated to a Path instance, and then their internal path strings are compared.
Parameters
other
Returns
FileExists()
static Boolean FileExists (Path path) static
Tests if the given file exists.
Parameters
path
Returns
Referenced by Asset.Path.CreateFolders().
FolderExists()
static Boolean FolderExists (Path path) static
Returns true if the folder exists. False otherwise, or if the path is to a file.
Parameters
path path to a file or folder
Returns
true if the folder exists
Referenced by Asset.Path.CreateFolders().
FromMeta()
static Path FromMeta (Path path) static
Returns the asset's file path from its .meta file path.
Parameters
path
Returns
Get() [1/2]
static Path Get (GUID guid) static
Gets the path of an asset file.
Parameters
guid
Returns
The path to the asset file, or null if the object is not an asset.
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                return String.IsNullOrEmpty(path) ? null : (Path)path;
            }
Get() [2/2]
static Path Get (Object obj) static
Gets the path of an asset file.
Parameters
obj
Returns
The path to the asset file, or null if the object is not an asset.
            {
                var path = AssetDatabase.GetAssetPath(obj);
                return String.IsNullOrEmpty(path) ? null : (Path)path;
            }
Referenced by Asset.VersionControl.CanMakeEditable(), Asset.Path.CreateFolders(), Asset.File.LoadMain< T >(), and Asset.Path.ToAssetPaths().
GetGuid()
static GUID GetGuid (Path path, AssetPathToGUIDOptions options = AssetPathToGUIDOptions.IncludeRecentlyDeletedAssets) static
Returns the GUID for the path. Returns an empty GUID if the asset at the path does not exist in the database. Exists ExistsInFileSystem
Parameters
path
options
Returns
GetHashCode()
override Int32 GetHashCode ()
Returns the internal path string's hash code.
Returns
GetScene()
static Path GetScene (Object obj) static
Returns the scene's path if the object is instantiated in a scene, otherwise returns the object's path.
Parameters
obj
Returns
GetSubFolders()
static String[] GetSubFolders (Path path) static
Returns the names of all subfolders in the path. Returns an empty array of the path points to a file.
Parameters
path
Returns
Paths to all subfolders, or empty array if there are no subfolders or the path points to a file.
IsValid()
static Boolean IsValid (String path) static
Returns true if the provided path is valid. This means it contains no illegal folder or file name characters and it isn't too long. If this returns false, Asset.GetLastErrorMessage() contains more detailed information. Asset.GetLastErrorMessage()
Parameters
path
Returns
True if the string is a valid path and contains no illegal characters for a path or file. False in all other cases.
            {
                var isValid = true;
                try
                {
                    // System.IO will throw for most illegal chars, plus some extra checks
                    var fileName = System.IO.Path.GetFileName(path);
                    var folderName = System.IO.Path.GetDirectoryName(path);
                    // check folder name for some chars that System.IO allows in GetDirectoryName
                    var testIllegalChars = new Func<Char, Boolean>(c => c == '*' || c == '?' || c == ':');
                    isValid = folderName.Any(testIllegalChars) == false;
                    if (isValid)
                    {
                        // check filename for some chars that System.IO allows in GetFileName
                        fileName = path.Substring(folderName.Length, path.Length - folderName.Length);
                        isValid = fileName.Any(testIllegalChars) == false;
                    }
                }
                catch (Exception ex)
                {
                    SetLastErrorMessage($"{ex.Message} => \"{path}\"");
                    isValid = false;
                }
                return isValid;
            }
OpenFolder()
void OpenFolder ()
Opens the folder externally, for example File Explorer (Windows) or Finder (Mac).
operator Path()
static implicit operator Path (String path) static
Implicit conversion of an AssetPath instance from a string path (full or relative).
Parameters
path
Returns
operator String()
static implicit operator String (Path path) static
Implicit conversion to string (relative asset path). Same as ToString().
Parameters
path
Returns
operator!=() [1/3]
static Boolean operator!= (Object other, Path path) static
Tests for inequality with an object.
Parameters
other
path
Returns
operator!=() [2/3]
static Boolean operator!= (Path path, Object other) static
Tests for inequality with an object.
Parameters
path
other
Returns
operator!=() [3/3]
static Boolean operator!= (Path path, Path path2) static
Tests two path instances for inequality.
Parameters
path
path2
Returns
operator==() [1/3]
static Boolean operator== (Object other, Path path) static
Tests for equality with an object.
Parameters
other
path
Returns
operator==() [2/3]
static Boolean operator== (Path path, Object other) static
Tests for equality with an object.
Parameters
path
other
Returns
operator==() [3/3]
static Boolean operator== (Path path, Path path2) static
Tests two path instances for equality.
Parameters
path
path2
Returns
            {
                if (ReferenceEquals(path, path2))
                    return true;
                if (ReferenceEquals(path, null))
                    return false;
                if (ReferenceEquals(path2, null))
                    return false;
                return path.Equals(path2);
            }
Rename()
Boolean Rename (String newFileOrFolderName)
Renames the file or folder with a new name.
Parameters
newFileOrFolderName
Returns
True if rename succeeded, false otherwise.
            {
                if (String.IsNullOrEmpty(newFileOrFolderName))
                    return false;
                m_RelativePath = $"{FolderPath}/{System.IO.Path.GetFileName(newFileOrFolderName)}";
                return true;
            }
ToAssetPaths()
static String[] ToAssetPaths (Object[] objects) static
Converts an array of objects to their asset paths. The returned array has the same size. Note that some items may be null if the input was null or not an asset.
Parameters
objects
Returns
            {
                ThrowIf.ArgumentIsNull(objects, nameof(objects));
                var objectCount = objects.Length;
                var paths = new String[objectCount];
                for (var i = 0; i < objectCount; i++)
                    paths[i] = Get(objects[i]);
                return paths;
            }
References Asset.Path.Get().
ToMeta()
static Path ToMeta (Path path) static
Returns the .meta file path from a path to an asset.
Parameters
path
Returns
ToString()
override String ToString ()
Returns the relative path as string. Same as implicit string conversion.
Returns
ToStrings()
static String[] ToStrings (IEnumerable< Path > paths) static
Converts a collection of Path instances to a string array.
Parameters
paths
Returns
Referenced by Asset.Database.ForceReserialize().
UniquifyFilename()
static Path UniquifyFilename (Path path) static
Returns the path either unaltered or with a numbering to make the file unique. This is only done if an asset file exists at the path. It does not alter folder paths. See also: Project Settings => Editor => Numbering Scheme Note: 'Uniquify' is a proper english verb, it means "to make unique".
Parameters
path
Returns
            {
                var uniquePath = AssetDatabase.GenerateUniqueAssetPath(path);
                return String.IsNullOrEmpty(uniquePath) ? path : uniquePath;
            }
Property Documentation
AssetPath
Path AssetPath get
Returns the path to the asset file if the path represents a .meta file.
Exists
Boolean Exists get
Returns true if the path exists in the AssetDatabase. NOTE: This may still return true for asset files that have been deleted externally. ExistsInFileSystem
            {
                get
                {
#if UNITY_2023_1_OR_NEWER
                    return AssetDatabase.AssetPathExists(m_RelativePath);
#else
                    return Guid.Empty() == false;
#endif
                }
            }
Referenced by Asset.File.Delete().
ExistsInFileSystem
Boolean ExistsInFileSystem get
Returns true if the path exists in the file system, be it file or folder. Returns false if the path does not exist. NOTE: This solely checks for physical existance, a new asset at that path may still not 'exist' in the database until it has been imported. Exists
Referenced by Asset.File.Import().
Extension
String Extension get
Returns the extension of the file path.
The extension with a leading dot (eg '.txt') or an empty string.
Referenced by Asset.Path.CreateFolders().
FileName
String FileName get
Returns the file name with extension.
FileNameWithoutExtension
String FileNameWithoutExtension get
Returns the file name without extension.
FolderPath
Path FolderPath get
Returns the relative path to the directory the file or folder is in. This means for folders it returns the parent folder.
Returns
The parent folder of the file or folder. Returns null if it's the root path.
            {
                get
                {
                    var dirName = System.IO.Path.GetDirectoryName(m_RelativePath);
                    return String.IsNullOrEmpty(dirName) ? null : dirName;
                }
            }
Referenced by Asset.Path.CreateFolders().
FullAssetsPath
String FullAssetsPath static get
Returns the path to the project's 'Assets' subfolder.
FullPackagesPath
String FullPackagesPath static get
Returns the path to the project's 'Packages' subfolder.
FullPath
String FullPath get
Creates and returns the full path, with forward slashes as separators.
FullProjectPath
String FullProjectPath static get
Returns the path to the project's root folder.
Guid
GUID Guid get
Returns the GUID for the path. Returns an empty GUID if the asset at the path does not exist in the database. Exists ExistsInFileSystem
Returns
Referenced by Asset.Path.CreateFolders().
MetaPath
Path MetaPath get
Returns the path to the .meta file if the path represents an asset file.
SubFolders
String [] SubFolders get
Returns the names of all subfolders in the current directory. If the path points to a file it returns an empty array, use "path.FolderPath.SubFolders" in this case.
UniqueFilePath
Path UniqueFilePath get
Returns the path either unaltered or with a numbering to make the file unique if an asset file already exists at the path. Does not alter path if it does not exist or points to a folder. See also: Project Settings => Editor => Numbering Scheme.