de.codesmile.editor.assetdatabase: Asset.Database Class Reference
Asset.Database Class Reference
Groups all asset database functionality. Turns out there isn't actually that much that is 'database' related after all.
Classes
class CacheServer
Groups CacheServer (Accelerator) related functionality.
Static Public Member Functions
static void AllowAutoRefresh ()
Will stop Unity from automatically importing assets. Must be called in pair with DisallowAutoRefresh. Multiple calls must be matched with an equal number of calls to DisallowAutoRefresh since internally this is using a counter that needs to return to 0 before auto refresh is going to be enabled again. Note: Has no effect if Preferences => Asset Pipeline => Auto Refresh is disabled to begin with. Same as AssetDatabase.AllowAutoRefresh(). DisallowAutoRefresh
static void DisallowAutoRefresh ()
Same as AssetDatabase.DisallowAutoRefresh(). AllowAutoRefresh
static void ForceReserialize (IEnumerable< Path > paths, ForceReserializeAssetsOptions options=ForceReserializeAssetsOptions.ReserializeAssetsAndMetadata)
Forces reserializing the assets as the given paths. This loads the assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
static void ForceReserialize (IEnumerable< String > paths, ForceReserializeAssetsOptions options=ForceReserializeAssetsOptions.ReserializeAssetsAndMetadata)
Forces reserializing the assets as the given paths. This loads the assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
static void ForceReserializeAll ()
Forces reserializing all assets. This loads all assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
static void ImportAll (ImportAssetOptions options=ImportAssetOptions.Default)
Formerly known as 'Refresh()', this scans for and imports assets that have been modified externally. External is defined as 'any file modification operation not done through the AssetDatabase', for example by using System.IO methods or by running scripts and other external tools.
static void ReleaseFileHandles ()
Releases any cached file handles Unity holds. May be required to allow manual asset or meta file modifications that bypass the AssetDatabase.
static void SaveAll ()
Saves all unsaved (dirty) objects. CAUTION: Consider that the user may NOT want to have unsaved assets 'randomly' saved! If you work with specific object(s) (which you do most of the time, right?) it is in your (user's) best interest if you use Asset.Save(obj) instead. Also consider using BatchEditing(Action) in that case.
Properties
static Int32 DesiredWorkerCount [get, set]
Gets or sets the desired worker count. Setting the worked count calls ForceToDesiredWorkerCount() to ensure the worker count is updated.
static Boolean DirectoryMonitoring [get]
Returns whether directory monitoring is enabled in Preferences, or disabled due to symlinks.
Detailed Description
Groups all asset database functionality. Turns out there isn't actually that much that is 'database' related after all.
Member Function Documentation
AllowAutoRefresh()
static void AllowAutoRefresh () static
Will stop Unity from automatically importing assets. Must be called in pair with DisallowAutoRefresh. Multiple calls must be matched with an equal number of calls to DisallowAutoRefresh since internally this is using a counter that needs to return to 0 before auto refresh is going to be enabled again. Note: Has no effect if Preferences => Asset Pipeline => Auto Refresh is disabled to begin with. Same as AssetDatabase.AllowAutoRefresh(). DisallowAutoRefresh
DisallowAutoRefresh()
static void DisallowAutoRefresh () static
Same as AssetDatabase.DisallowAutoRefresh(). AllowAutoRefresh
ForceReserialize() [1/2]
static void ForceReserialize (IEnumerable< Path > paths, ForceReserializeAssetsOptions options = ForceReserializeAssetsOptions::ReserializeAssetsAndMetadata) static
Forces reserializing the assets as the given paths. This loads the assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
ForceReserialize()
Parameters
paths
options
            {
                ThrowIf.ArgumentIsNull(paths, nameof(paths));
                ForceReserialize(Path.ToStrings(paths), options);
            }
References Asset.Database.ForceReserialize(), and Asset.Path.ToStrings().
Referenced by Asset.Database.ForceReserialize().
ForceReserialize() [2/2]
static void ForceReserialize (IEnumerable< String > paths, ForceReserializeAssetsOptions options = ForceReserializeAssetsOptions::ReserializeAssetsAndMetadata) static
Forces reserializing the assets as the given paths. This loads the assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
ForceReserialize()
Parameters
paths
options
            {
                ThrowIf.ArgumentIsNull(paths, nameof(paths));
                AssetDatabase.ForceReserializeAssets(paths, options);
            }
ForceReserializeAll()
static void ForceReserializeAll () static
Forces reserializing all assets. This loads all assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
ForceReserialize(System.Collections.Generic.IEnumerable<CodeSmile.Editor.Asset.Path>,UnityEditor.ForceReserializeAssetsOptions)
ImportAll()
static void ImportAll (ImportAssetOptions options = ImportAssetOptions.Default) static
Formerly known as 'Refresh()', this scans for and imports assets that have been modified externally. External is defined as 'any file modification operation not done through the AssetDatabase', for example by using System.IO methods or by running scripts and other external tools.
Note: the 100% accurate name for this method would have to be: ImportAllExternallyModifiedAssetsAndAlsoUnloadUnusedAssets()
CAUTION: Calling this may have an adverse effect on editor performance. In addition to scanning for changed files it also calls Resources.UnloadUnusedAssets internally and it also discards any unsaved objects not marked as 'dirty' that are only referenced by scripts, leading to potential loss of unsaved data. https://docs.unity3d.com/Manual/AssetDatabaseRefreshing.html
File.Import
Parameters
options
ReleaseFileHandles()
static void ReleaseFileHandles () static
Releases any cached file handles Unity holds. May be required to allow manual asset or meta file modifications that bypass the AssetDatabase.
SaveAll()
static void SaveAll () static
Saves all unsaved (dirty) objects. CAUTION: Consider that the user may NOT want to have unsaved assets 'randomly' saved! If you work with specific object(s) (which you do most of the time, right?) it is in your (user's) best interest if you use Asset.Save(obj) instead. Also consider using BatchEditing(Action) in that case.
Asset.Save Asset.ForceSave Asset.File.BatchEditing
Property Documentation
DesiredWorkerCount
Int32 DesiredWorkerCount static get set
Gets or sets the desired worker count. Setting the worked count calls ForceToDesiredWorkerCount() to ensure the worker count is updated.
            {
                get => AssetDatabase.DesiredWorkerCount;
                set
                {
                    AssetDatabase.DesiredWorkerCount = value;
                    AssetDatabase.ForceToDesiredWorkerCount();
                }
            }
DirectoryMonitoring
Boolean DirectoryMonitoring static get
Returns whether directory monitoring is enabled in Preferences, or disabled due to symlinks.