de.codesmile.editor.assetdatabase: CodeSmile.Editor.Asset.Label Class Reference
CodeSmile.Editor.Asset.Label Class Reference
Groups all asset label related static methods.
Static Public Member Functions
static void Add (Object obj, String label)
Adds a label to an asset's list of labels. Note: this is less efficient than SetLabels. It is provided as a convenience to add a few labels without having to do the conversion to List, then add a label, then ToArray() the list. This is what is done internally.
static void Add (Object obj, String[] labels)
Adds several labels to an asset's list of labels.
static void ClearAll (Object obj)
Clears all labels of an asset.
static String[] GetAll (GUID guid)
Returns an asset's labels.
static String[] GetAll (Object obj)
Returns an asset's labels.
static void SetAll (Object obj, String[] labels)
Sets an asset's labels, replacing any existing labels.
Detailed Description
Groups all asset label related static methods.
Member Function Documentation
Add() [1/2]
static void CodeSmile.Editor.Asset.Label.Add (Object obj, String label) static
Adds a label to an asset's list of labels. Note: this is less efficient than SetLabels. It is provided as a convenience to add a few labels without having to do the conversion to List, then add a label, then ToArray() the list. This is what is done internally.
Add(UnityEngine.Object,string[])
Parameters
obj
label
            {
                var existingLabels = new List<String>(GetAll(obj));
                existingLabels.Add(label);
                AssetDatabase.SetLabels(obj, existingLabels.ToArray());
            }
References CodeSmile.Editor.Asset.Label.GetAll().
Add() [2/2]
static void CodeSmile.Editor.Asset.Label.Add (Object obj, String[] labels) static
Adds several labels to an asset's list of labels.
Add(UnityEngine.Object,string)
Parameters
obj
labels
            {
                var existingLabels = new List<String>(GetAll(obj));
                existingLabels.AddRange(labels);
                AssetDatabase.SetLabels(obj, existingLabels.ToArray());
            }
References CodeSmile.Editor.Asset.Label.GetAll().
ClearAll()
static void CodeSmile.Editor.Asset.Label.ClearAll (Object obj) static
Clears all labels of an asset.
Parameters
obj
GetAll() [1/2]
static String[] CodeSmile.Editor.Asset.Label.GetAll (GUID guid) static
Returns an asset's labels.
Parameters
guid
Returns
GetAll() [2/2]
static String[] CodeSmile.Editor.Asset.Label.GetAll (Object obj) static
Returns an asset's labels.
Parameters
obj
Returns
Referenced by CodeSmile.Editor.Asset.Label.Add().
SetAll()
static void CodeSmile.Editor.Asset.Label.SetAll (Object obj, String[] labels) static
Sets an asset's labels, replacing any existing labels.
Parameters
obj
labels
The documentation for this class was generated from the following file:
Editor/Asset.Labels.cs