CodeSmile AssetDatabase: CodeSmile.Editor.Asset.Path.CreateFolders
CreateFolders() [2/2]
static GUID CreateFolders (Path path) static
Creates any missing folders in the path.
Unlike AssetDatabase.CreateFolder this creates the entire path in one go rather than each folder one by one.
Path may point to either a file or folder. If the last path element has an extension it is considered a file.
Parameters
path Path to a file or folder.
Returns
GUID of the deepest (last) folder in the path.
See also
AssetDatabase.CreateFolder
Definition at line 254 of file Asset.Path.Static.cs.
            {
                ThrowIf.ArgumentIsNull(path, nameof(path));
                ThrowIf.PathIsNotValid(path);
                if (FileExists(path))
                    return path.FolderPath.Guid;
                // if the last part has an extension we assume the path points to a file
                var isPresumablyFilePath = String.IsNullOrEmpty(path.Extension) == false;
                var folderPath = isPresumablyFilePath ? path.FolderPath : path;
                if (FolderExists(folderPath))
                    return folderPath.Guid;
                var folderNames = ((String)folderPath).Split(new[] { '/' });
                var folderGuid = GuidForExistingPath(folderNames[0]); // first is "Assets"
                var partialPath = folderNames[0];
                for (var i = 1; i < folderNames.Length; i++)
                {
                    partialPath += $"/{folderNames[i]}";
                    if (FolderExists(partialPath))
                    {
                        folderGuid = GuidForExistingPath(partialPath);
                        continue;
                    }
                    folderGuid = CreateSubFolder(Get(folderGuid), folderNames[i]);
                }
                return folderGuid;
            }
References Asset.Path.FileExists(), Asset.Path.FolderExists(), and Asset.Path.Get().