de.codesmile.editor.assetdatabase: CodeSmile.Editor.Asset.Database.ForceReserialize
ForceReserialize() [1/2]
static void CodeSmile.Editor.Asset.Database.ForceReserialize (IEnumerable< Path > paths, ForceReserializeAssetsOptions options = ForceReserializeAssetsOptions::ReserializeAssetsAndMetadata) static
Forces reserializing the assets as the given paths. This loads the assets, upgrades them to their current serialization version, and then writes them back to disk. Note: this can potentially change a lot of files in version control. It should be done cautiously.
ForceReserialize()
Parameters
paths
options
            {
                ThrowIf.ArgumentIsNull(paths, nameof(paths));
                ForceReserialize(Path.ToStrings(paths), options);
            }
References CodeSmile.Editor.Asset.Database.ForceReserialize(), and CodeSmile.Editor.Asset.Path.ToStrings().
Referenced by CodeSmile.Editor.Asset.Database.ForceReserialize().